plugin:
    name: 'webbook.checkcontent::lang.plugin.name'
    description: 'webbook.checkcontent::lang.plugin.description'
    author: WebBook
    icon: oc-icon-info
    homepage: 'https://webbook.page/plugins'
